### ISSUE TITLE
[Feature Request] Support for Greedy Meshing

### ISSUE THREAD

**Issue by HeadClot** [vagenv/BlockConstructor#1] opened 2016-04-28 03:41 UTC
Hey @vagenv -

Got a feature request for this awesome plugin. There is a common Technique used in Voxel games called Greedy meshing. This should greatly improve performance.

Here is a video of it in action -
https://www.youtube.com/watch?v=0OZxZZCea8I

Here is some example Code for you to get an Idea. [Link](https://github.com/roboleary/GreedyMesh)

If you need more info please let me know. :)

- HeadClot

**Comment by vagenv** [comment] 2016-04-28 12:41
The problem is that this plugin is not using Voxels at ALL.
This plugin is extension of UInstantStaticMeshComponent with some upper layer control.

Generally I optimized the managing of Instance data in such a way that it would not require "Flush" of data at every modification.

I am just adding instances and scaling them. 

Therefore when rendering data on GPU I am just passing a cube mesh and array of position and scale.

**Comment by fesoliveira014** [comment] 2016-04-29 05:06
Hello vagenv, I am writting an voxel engine from scratch, and on my engine voxels are actually draw using triangle meshed, the same way yours are. Since you store your block data in grid-like data structure, your cubes could easily be merged using greedy meshing. Your MegaBlocks as you call are actually the same as voxel chunks, since each position on the regular grid can either be empty of contain a cube. If you want a reference on the implementation of greedy meshing in C++, feel free to take a look at my implementation of it: [ChunkMesher.cpp](https://github.com/fesoliveira014/cubeproject/blob/master/CubeProject/tactical/volume/mesher/ChunkMesher.hpp). By the way, the correct implementation is the Greedy(...) function. Greedy2 is an optimization attempt that failed lol.

**Comment by vagenv** [comment] 2016-04-29 13:04
I am really sorry if I didn't explain correctly.

I created a method similar to "Greedy Meshing" which searches and finds the biggest block which in turn are [MegaBlock].
Method [FMegaBlockFinder] is optimizing thread which does exactly that.

[LeveBlockConstructor] class which is a counterpart of the [Chunk] which is used in voxels.

The big difference is that this plugin doesn't work with or have data about vertices,triangles or polygons at all.

**Closed** 2016-05-01 16:00 UTC
